spring.application.name=Alumni-FIA-UES-Backend
server.port=${SERVER_PORT:8080}

spring.jpa.open-in-view=false

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=${SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:900000}

azure.storage.connection-string=${AZURE_STORAGE_CONNECTION_STRING}
azure.communication.connection-string=${AZURE_COMMUNICATION_CONNECTION_STRING}
azure.communication.sender-address=${AZURE_SENDER_EMAIL:DoNotReply@YOUR_DOMAIN.azurecomm.net}
azure.communication.sender-name=${AZURE_SENDER_NAME:Notificaciones Alumni FIA}


azure.storage.container-name=${AZURE_STORAGE_CONTAINER_NAME}
azure.storage.blob-url=${AZURE_STORAGE_BLOB_URL}

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB


frontend.url=${FRONTEND_URL:http://localhost:4200}

logging.level.root=INFO
logging.level.org.fia.alumni.alumnifiauesbackend=DEBUG



